nobleworkshop/mywalit

src/less/base/_variables.less
src/less/blocks/_buttons.less
src/pug/mixins/_buttons.pug
src/pug/pages/ui/buttons.pug

Реализованы кнопки. Для кнопки Подробнее сделала синий фон, т.к. белое на белом не видно, у самой кнопки такого синего фона не будет.

added ui-buttons

---

gulpfile.js
src/img/icons/gamburger.svg
src/js/main.js
src/less/base/_variables.less
src/less/blocks/_colors.less
src/less/main.less
src/less/sections/_header-nav.less
src/pug/layouts/page-layout/_head.pug
src/pug/layouts/ui-layout/_head.pug
src/pug/pages/ui/header-nav.pug
src/pug/sections/header-nav.pug
src/pug/sections/ui-navigation.pug

1. Добавлен блок с навигацией меню
2. Добавлен градиент для меню отдельный (он не меняется в отличие от основного)

Header nav

---

src/less/sections/_header-top.less
src/pug/pages/ui/header-top.pug
src/pug/sections/header-top.pug

header top fix

---

src/less/sections/_footer-navigation.less
src/less/sections/_footer-subscribe.less
src/less/sections/_footer.less
src/pug/pages/ui/footer-navigation.pug
src/pug/pages/ui/footer-subscribe.pug
src/pug/pages/ui/footer.pug
src/pug/pages/ui/forms.pug
src/pug/sections/ui-navigation.pug

@nobleworkshop вроде готов. Делала по сетке. С отступом в offset-1... Но мне кажется есть небольшое несоответствие макету. Может я что-то не так сделала...

footer is done

---

src/pug/pages/ui/footer.pug
src/pug/sections/footer.pug

added pre include

---

package.json
src/less/blocks/_section-card.less
src/pug/pages/ui/catalogue-section.pug

Олег, добавила дополнительные точки перелома для наезжающих картинок  в разделах каталога

add new media points

---

src/less/blocks/_card-product.less
src/less/blocks/_sales-hits.less
src/less/blocks/_titles.less
src/pug/mixins/_cards.pug
src/pug/pages/main.pug
src/pug/pages/ui/cards.pug
src/pug/pages/ui/sales_hits.pug

заголовок карточки продукта определен, как ссылка. Увидеть результат можно в разделе Блоки -Карточка продукта.

add title-link

---

src/js/city-selector.js
src/js/main.js
src/pug/layouts/page-layout/_foot.pug

1. Вынес скрипт для городов в отельный файл анонимной функцией.
2. При мобильной навигации убрал скроллинг у основной страницы.
3. Чуть поднастроил кастомный скролинг.

separate script file for city selector

---

src/pug/mixins/_input.pug
src/pug/pages/ui/forms.pug

Исправила расстояние между инпутом и ошибкой, в случае добавление марджина. Делаю мерж в девелоп.

fixed input and error distance

---

src/js/main.js

1. Скрывать блок при клике вне блока
2. Немного обновил скрипт.

script updated

---

src/less/blocks/_drop-down.less
src/less/blocks/_filter.less
src/less/pages/catalog.less
src/pug/mixins/_color-line.pug
src/pug/pages/catalog.pug

Сделан баг фикс страницы Каталог

fixed bugs catalog page

---

src/less/blocks/_drop-down.less
src/less/blocks/_filter.less
src/less/pages/catalog.less
src/less/sections/_header-nav.less
src/less/sections/_header-search.less
src/pug/mixins/_color-line.pug
src/pug/pages/catalog.pug
src/pug/pages/ui/header-nav.pug
src/pug/pages/ui/header-search.pug
src/pug/sections/header-nav.pug
src/pug/sections/header-search.pug

Fix gradient 050918

---

src/less/pages/catalog.less

Фильтр отображался не на всю ширину на мобильных устройствах. Исправила.

fixed filter mobile

---

src/js/modal-window.js

1. Добавлено закрытие модального окна по клику вне его области.

modal window

---

src/js/main.js
src/less/pages/catalog.less

Задача Страница Каталог. z-index у фильтра перекрывает поиск

z index fixed and full screen mobile filter

---

src/less/blocks/_show-order.less
src/less/main.less
src/less/sections/_thanks-for-ordering.less
src/pug/mixins/_show-order.pug
src/pug/pages/ui/thanks-for-ordering.pug
src/pug/sections/thanks-for-ordering.pug
src/pug/sections/ui-navigation.pug

копия ветки thanks-for-ordering которую смержила в мастер. Эта копия для мержа в девелоп

Thanks ordering for develop

---

src/less/blocks/_sections.less
src/less/sections/_thanks-for-ordering.less
src/pug/pages/order-processed.pug
src/pug/sections/ui-navigation.pug

Добавлена страница Order-processed

Order processed page

---

src/less/blocks/_bread-crumb.less
src/less/blocks/_sections.less
src/less/blocks/_vertical-navigation.less
src/less/main.less
src/less/pages/account-profile.less
src/less/sections/_contact-info.less
src/pug/pages/account-profile.pug
src/pug/pages/ui/profile-contacts.pug
src/pug/sections/_contacts-profile.pug
src/pug/sections/ui-navigation.pug

1. Страница Account-profile готова

account-profile page completed

---

src/less/blocks/_sections.less
src/less/main.less
src/less/pages/account-favourite.less
src/pug/pages/account-favourite.pug
src/pug/pages/index.pug
src/pug/sections/_contacts-profile.pug
src/pug/sections/ui-navigation.pug

1. Добавлена страница Account-favourite
2. Обновлена index.html
3. В шапке изменен отступ слева у первого элемента для планшета (согласно дизайну)

Account favourite page

---

src/pug/sections/contacts-info.pug

изменено "кредитная карта" на "банковская карта"
Готово к проверке!

Contact info fix

---

src/less/sections/_footer-subscribe.less

Для заголовка формы подписки добавлен нижний отступ 16 пкс 
.footer-bottom .title-4 {
margin: 0 0 16px 0;
}
Готово к проверке

add mb-16 for title-4

---

src/less/sections/_contact-info.less
src/pug/sections/contacts-info.pug

установлено значение 600 для толщины текста

add font-weight: 600

---

src/less/blocks/_inputs.less

для удаления крестика в конце строки добавила волшебные строчки 
.someinput::-ms-clear {
display: none;
}

edit input

---

src/less/pages/page404.less

на положение смайлика влияет отступ margin-top для svg-container, заменила значение -150пкс на 0 пкс

small magrin-top gor svg-container

---

src/less/blocks/_card-product.less

Задана максимальная ширина для текста

add max-width 99%

---

src/less/blocks/_card-product.less
src/less/blocks/_section-card.less
src/less/blocks/_show-order.less
src/pug/pages/ui/job-modal.pug
src/pug/pages/ui/show-order.pug

задана для текста максимальная ширина 99%

add max-width for text

---

src/less/blocks/_buttons.less
src/less/sections/_footer.less
src/pug/pages/ui/footer-navigation.pug

добавила для навигации минимальную высоту

add min-height

---

src/js/goods-cart.js

При нажатии вернуться в каталог пропадал скролл основной страницы. Сделан фикс.

Исправлена ошибка скролла

---

src/less/blocks/_inputs.less
src/less/blocks/_profile-contacts.less
src/less/sections/_contact-info.less
src/pug/pages/ui/show-order.pug
src/pug/sections/show-order.pug

1. сообщение об ошибке при заполнении поля поднято выше, ближе к инпуту
2. текст "Ведите номер клубной карты" оказался большой длины и  выстраивался в две строки, когда он поднимается вверх  в момент, клика по инпуту. Поэтому заменили его на текст "Номер клубной карты"

Fix 13 09 18

---

src/less/blocks/_banner.less
src/less/blocks/_login-forms.less

для формы регистрации/авторизации маргин-боттом на мобильной версии установлен 16 пкс

edit mb-16 for login-form

---

src/less/blocks/_accordeon-job.less

Внесены правки для размера заголовка аккордеона на странице вакансии  на экранах desktop и desktopXL

edit job-accordeon title font size

---

src/pug/pages/product.pug

на странице Описание товара цвета продукта оформлены в виде ссылки

add link for product-color

---

src/js/products-table.js

Теперь открывается только один заказ, остальные закрываются.

Фикс скрипта в заказах

---

src/less/sections/_header-nav.less

Фикс перекрывания dropdown выпадающего списка меню

---

src/less/sections/_footer-subscribe.less
src/pug/pages/ui/footer-subscribe.pug
src/pug/sections/_footer-subscribe.pug

Заменен заголовок формы подписки в футере 
добавлен заголовку дополнительный класс  .footer-subscribe__slogan для его стиллизации

change footer slogan

---

src/js/goods-cart.js
src/js/main.js
src/pug/layouts/page-layout/_foot.pug
src/pug/layouts/ui-layout/_foot.pug
src/pug/pages/shops.pug

Сделан фикс скрипта, при котором скрипт удаления корзины при клике вне бока, затрагивал так же меню.

Фикс убрать корзину при клике вне

---

src/js/main.js
src/less/base/_base.less
src/less/blocks/_form-contact-page.less
src/less/main.less
src/pug/pages/ui/form-contact-page.pug
src/pug/sections/ui-navigation.pug

UI-Kit - Блоки - Форма на странице Контакты ( ui/form-contact-page.html )

Форма дял страницы Контакты

---

src/less/blocks/_shop-contacts.less
src/less/main.less
src/pug/pages/ui/shop-contacts.pug
src/pug/sections/ui-navigation.pug

shop-contacts-first-commit

---

src/less/blocks/_form-contact-page.less
src/pug/pages/contacts.pug
src/pug/pages/index.pug
src/pug/sections/ui-navigation.pug

На главной страницы - Контакты магазинов или в Ui-kit Страницы - Контакты магазинов

Страница контакты магазинов

---

src/js/city-selector.js
src/less/blocks/_city-selection.less

1. Удален кастомный скролл для городов, так как мерцал при загрузки страницы.

custom scroll removed for cities

---

src/js/drop-down.js
src/js/main.js
src/less/base/_base.less
src/less/blocks/_drop-down.less
src/pug/layouts/page-layout/_foot.pug
src/pug/layouts/ui-layout/_foot.pug
src/pug/pages/catalog.pug
src/pug/pages/ui/drop-down.pug

Изменена реализация выпадающего списка на select - option

Change drop list

---

src/pug/mixins/_filter-menu.pug

для того, что бы при наведении на кружочек с цветом в фильтре появлялось название цветов, добавлен параметр title  для дива, в котором находится img с цветом

add title for color
